import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar";
import Instagram from "./ui/Instagram";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pixel-Pals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <Navbar />
          {children}
          <Instagram/>
        </>
      </body>
    </html>
  );
}
